[module.hugoVersion]
extended = false
min = "0.56.0"

[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "layouts"
target = "layouts"

[outputFormats]
[outputFormats.OpenSearch]
mediatype = "application/opensearchdescription+xml"
baseName = "opensearch"
isPlainText = true
notAlternative = true

[mediaTypes]
[mediaTypes."application/opensearchdescription+xml"]
suffixes = ["xml"]
delimiter = ""
