[module.hugoVersion]
extended = false
min = "0.56.0"

[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "i18n"
target = "i18n"

[[module.mounts]]
source = "layouts"
target = "layouts"

# either:
# copy this section into your own configuration
# or:
# add `_merge = "deep"` into the `[outputFormats]` section of your configuration
[outputFormats]
[outputFormats.OpenSearch]
mediatype = "application/opensearchdescription+xml"
baseName = "opensearch"
isPlainText = true
notAlternative = true

# either:
# copy this section into your own configuration
# or:
# add `_merge = "deep"` into the `[mediaTypes]` section of your configuration
[mediaTypes]
[mediaTypes."application/opensearchdescription+xml"]
suffixes = ["xml"]
delimiter = "."

# parameters
[params]
[params.dnb.opensearch]
hookLink = "https://dnbql.netlify.app/opensearch"
