################################################################################
# configuration
################################################################################
[module.hugoVersion]
extended = false
min = "0.71.0"

[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "layouts"
target = "layouts"
