################################################################################
# configuration
################################################################################
[module.hugoVersion]
extended = false
min = "0.71.0"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "data/dnb/renderhooks"
target = "data/dnb/renderhooks"
