name = "DNB Hugo Robots.txt"
license = "MIT"
licenselink = "https://github.com/dnb-org/components/blob/master/sitemap/LICENSE"
description = "A robots.txt for Hugo."
homepage = "https://github.com/dnb-org/components"
tags = ["robots.txt"]
features = ["robots.txt"]
min_version = "0.71.0"

[author]
  name = "Patrick Kollitsch"
  homepage = "https://davids-neighbour.com/"
