################################################################################
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
################################################################################
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "22:15"
      timezone: "Asia/Bangkok"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999

  - package-ecosystem: "npm"
    directory: "/favicon"
    schedule:
      interval: "daily"
      time: "22:15"
      timezone: "Asia/Bangkok"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999

  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "daily"
      time: "22:15"
      timezone: "Asia/Bangkok"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999

  - package-ecosystem: "npm"
    directory: "/netlification"
    schedule:
      interval: "daily"
      time: "22:15"
      timezone: "Asia/Bangkok"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999

  - package-ecosystem: "npm"
    directory: "/renderhooks"
    schedule:
      interval: "daily"
      time: "22:15"
      timezone: "Asia/Bangkok"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999

  - package-ecosystem: "npm"
    directory: "/robots"
    schedule:
      interval: "daily"
      time: "22:15"
      timezone: "Asia/Bangkok"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999

  - package-ecosystem: "npm"
    directory: "/search-algolia"
    schedule:
      interval: "daily"
      time: "22:15"
      timezone: "Asia/Bangkok"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999

  - package-ecosystem: "npm"
    directory: "/sitemap"
    schedule:
      interval: "daily"
      time: "22:15"
      timezone: "Asia/Bangkok"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
