################################################################################
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
################################################################################
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "npm"
    directory: "/auditor"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "npm"
    directory: "/netlification"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "npm"
    directory: "/opensearch"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "npm"
    directory: "/pwa"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "npm"
    directory: "/renderhooks"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "npm"
    directory: "/robots"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "npm"
    directory: "/search-algolia"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "npm"
    directory: "/security"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "npm"
    directory: "/sitemap"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "npm"
    directory: "/social"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/search-algolia"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"

  - package-ecosystem: "gomod"
    directory: "/social"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "18:00"
      timezone: "Asia/Bangkok"
    assignees:
      - "davidsneighbour"
    reviewers:
      - "davidsneighbour"
    target-branch: "main"
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: "/"
    labels:
      - "type:dependencies"
