##################################################################################
# Functions used in dnb-hugo themes
##################################################################################
# see https://gohugo.io/templates/output-formats/
# see https://gohugo.io/news/http2-server-push-in-hugo/
# see https://gohugo.io/hugo-modules/theme-components/

[module.hugoVersion]
extended = true
min = "0.78.0"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "data/dnb/functions/readingtime"
target = "data/dnb/functions/readingtime"
