name = "DNB Hugo Shortcodes"
license = "Apache 2.0"
licenselink = "https://github.com/davidsneighbour/dnb-hugo-shortcodes/blob/master/LICENSE"
description = "Hugo shortcodes used in David's Neighbour's themes. Yes, double genitive."
homepage = "https://github.com/davidsneighbour/dnb-hugo-shortcodes"
tags = ["shortcodes"]
features = ["shortcodes"]
min_version = "0.56"

[author]
  name = "Patrick Kollitsch"
  homepage = "https://davids-neighbour.com/"
