name = "DNB Hugo Sitemap"
license = "MIT"
licenselink = "https://github.com/dnb-hugo/components/blob/master/sitemap/LICENSE"
description = "A sitemap for Hugo."
homepage = "https://github.com/dnb-hugo/components"
tags = ["sitemap"]
features = ["sitemap"]
min_version = "0.56.0"

[author]
  name = "Patrick Kollitsch"
  homepage = "https://davids-neighbour.com/"
