[hugoVersion]
extended = false
min = "0.56.0"

[[mounts]]
source = "assets"
target = "assets"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "layouts"
target = "layouts"

[[imports]]
path = "github.com/dnb-org/components/functions"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/dnb-org/debug"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/dnb-org/hooks"
disable = false
ignoreConfig = false
ignoreImports = false
