[module.hugoVersion]
extended = false
min = "0.56.0"

[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "i18n"
target = "i18n"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "static"
target = "static"
