name = "DNB Hugo +++pLACEHOLDER+++"
license = "MIT"
licenselink = "https://github.com/dnb-hugo/components/blob/master/+++PLACEHOLDER+++/LICENSE"
description = "tbd"
homepage = "https://github.com/dnb-hugo/components"
tags = ["netlify", "hugo", "hugo-theme-component"]
features = ["tbd"]
min_version = "0.56.0"

[author]
  name = "Patrick Kollitsch"
  homepage = "https://github.com/dnb-hugo/components/"
