backend:
  name: git-gateway
  branch: main
media_folder: static/img
public_folder: /img
collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts{{year}}/{{month}}'
    path: '{{slug}}/index.md'
    create: true
    slug: ''
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
