[module.hugoVersion]
extended = false
min = "0.56.0"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "data"
target = "data"

[[module.imports]]
path = "github.com/davidsneighbour/dnb-hugo/functions"
disabled = false
